### ISSUE TITLE
Fix: Hide user password at response

### ISSUE THREAD

**Issue by ndabAP** [ndabAP/vue-sails-example#23]
E. g., products API endpoint returns users passwords.

**Comment by ndabAP** [comment]
E. g., products API endpoint returns users passwords.

**Comment by qvdp** [comment]
Hi, i don't know if this is still a problem, but you might be able to add a setting function at the bottom of the `api > models > user.js` file such as :

```
// Return a shallow copy of this record with certain attributes removed at each request
customToJSON () {
    return _.omit(this, ['password']);
}
```
 More info, [here](https://sailsjs.com/documentation/concepts/models-and-orm/model-settings#?customtojson).

**Comment by ndabAP** [comment]
Hey @qvdp, yeah, this is still a problem. I guess I tried your solution some time ago and it didn't work. But I'll try is again.

Would it be possible for you to provide the full file `user.js`?
