### ISSUE TITLE
Fresh Project

### ISSUE THREAD

**Issue by steventhanna** [ndabAP/vue-sails-example#31]
This project has been a great example of how everything fits together, and I would like to use this system in an upcoming project.  However, I am having some trouble setting up and configuring a fresh project to mirror yours.  This information can prove to be an invaluable resource.  Anything that you could provide would be greatly appreciated.

**Comment by ndabAP** [comment]
@steventhanna thanks for your words. What exactly is your problem? My approach would be:

1. Clone the project
2. delete the components and controllers
3. start from here.

**Comment by steventhanna** [comment]
Thanks for your quick response.  I was trying to replicate from a fresh build, but I will try that.

**Comment by steventhanna** [comment]
I stripped everything out, and got everything to work correctly.  I also created a starter template for anyone else who might be interested.  Thanks again

[vue-sails-template](https://github.com/steventhanna/vue-sails-template)

**Comment by ndabAP** [comment]
That's very cool! Thanks a lot. Hope you enjoy working with it.

**Comment by ndabAP** [comment]
@steventhanna I added your template the projects readme.
