### ISSUE TITLE
In the compiled js file my absolute path is public visible

### ISSUE THREAD

**Issue by zimudec** [ndabAP/vue-sails-example#32]
When building files with "npm run build", the js libraries are compiled in a single file (the heaviest js), but I realized that in that file, the absolute paths of each library appear (path of my team where I built), and it's visible in that public archive! That should not be good.

**Example:** 

File: http://localhost:1337/assets/js/0.51144fbc4d9e52d0f2b2.js
Content example: ...{version:3,sources:["/home/.../frontend/src/App.desktop.vue"]... 

How can it be corrected so that they do not appear?

**Comment by ndabAP** [comment]
Nice catch. The same applies to the built files:

https://github.com/ndabAP/vue-sails-example/blob/master/backend/assets/assets/js/0.029968c345e14ba2568b.js

Well, you're right, this shouldn't be visible. But it's something that comes with the Vue.js/Webpack setup. I didn't set it to be like that. Some more investigation is necessary.

**Comment by zimudec** [comment]
> https://github.com/ndabAP/vue-sails-example/blob/master/backend/assets/assets/js/0.029968c345e14ba2568b.js

Yes, I also saw it, I forgot to comment on it.

> Well, you're right, this shouldn't be visible. But it's something that comes with the Vue.js/Webpack setup. I didn't set it to be like that. Some more investigation is necessary.

I'm not sure, but I think the problem is in the "new webpack.optimize.CommonsChunkPlugin (" function
