### ISSUE TITLE
SSR with Vue?

### ISSUE THREAD

**Issue by amirakbulut** [ndabAP/vue-sails-example#73]
How is this project able of rendering the html of it's Vue components to the browser? I thought only Nuxt.js was capable of doing that.

**Comment by ndabAP** [comment]
I don't understand the question. The project never uses HTLM strings from server

**Comment by amirakbulut** [comment]
With Vue, everything that's rendered in the client isn't visible in the source of the page. That's why Vue isn't SEO friendly, Nuxt.js solves this by rendering on the server itself. However, you're using Vue and I can still see everything in the source..?

**Comment by ndabAP** [comment]
> I can still see everything in the source..?

I [don't](view-source:https://vue-sails-example.herokuapp.com/) ;)

**Comment by ndabAP** [comment]
Closing, since not an issue.
