### ISSUE TITLE
Sails.js testing?

### ISSUE THREAD

**Issue by Noitidart** [ndabAP/vue-sails-example#74]
I found this repo from a link on reddit when I was trying to learn Sails.js testing. I see your tests here are also lacking what i am trying to do:

I am also looking for Sails.js beginners out-of-the-box guide for testing, similar to Laravel doc here - https://laravel.com/docs/5.7/testing - sails.js only has this - https://sailsjs.com/documentation/concepts/testing - but this is greatly lacking. It makes clear that boilerplate is needed but I can't get that boilerplate to do:

* Before running each test file, it should clean everything to as if it was just `sails.lift()`ed and `bootstrap` run
* Use `Cloud` SDK in tests
* Use seperate database and port for testing so it doesnt affect the dev database
* Creating and loading fixtures before certain tests

Does anyone have any super beginners guide for testing in Sails.js?

**Comment by ndabAP** [comment]
@Noitidart this is one of the reasons I left Sails.js and moved over to Express.js :)

**Comment by Noitidart** [comment]
Ah, thank you brother for such a fast reply! And leaving for me to close.
